Repository eclipse/xtext-xtend, pull requests merged in 2018-05, with the labels that each got.

#441 [#440] Enable run action for JUnit 5 tests
  org.eclipse.xtend.ide/plugin.xml
Labels: new_feature

#445 [eclipse/xtext#1198] Update Orbit URL to Photon M7
  releng/org.eclipse.xtend.target/org.eclipse.xtend.target-luna.target
  releng/org.eclipse.xtend.target/org.eclipse.xtend.target-oxygen.target
  releng/org.eclipse.xtend.target/org.eclipse.xtend.target-photon.target
Labels: releng

#446 fixed broken example
  org.eclipse.xtend.examples/projects/xtend-euler/.settings/org.eclipse.jdt.core.prefs
Labels: bug

#451 [#324] regenerated docs
  org.eclipse.xtend.doc/contents/203_xtend_expressions.html
Labels: documentation
