Repository eclipse/xtext-xtend, pull requests merged in 2018-10, with the labels that each got.

#589 Xtext Bootstrap 2.15
  gradle/bootstrap-setup.gradle
  gradle/versions.gradle
  releng/org.eclipse.xtend.tycho.parent/pom.xml
Labels: releng

#598 Xtend-examples: Fix broken link to the Xtend operators documentation.
  org.eclipse.xtend.examples/projects/xtend-examples/src/example2/BasicExpressions.xtend
Labels: bug

#585 [#582] Evaluate bootclasspath only for Java <= 1.8
  org.eclipse.xtend.core/src/org/eclipse/xtend/core/compiler/batch/XtendBatchCompiler.java
  org.eclipse.xtend.maven.plugin/src/main/java/org/eclipse/xtend/maven/AbstractXtendCompilerMojo.java
Labels: enhancement

#597 [eclipse/xtext#1300] Update to Gradle Wrapper 4.10.2
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: releng

#588 [eclipse/xtext#1222] Auto-detect upstream repository URLs
  build.gradle
  gradle/upstream-repositories.gradle
Labels: enhancement, releng

#603 [eclipse/xtext#1222] fixed branch detection on Jenkins
  gradle/upstream-repositories.gradle
Labels: releng

#604 [eclipse/xtext-umbrella#65] Adjust upstream branch
  releng/org.eclipse.xtend.maven.parent/pom.xml
Labels: releng

#605 [eclipse/xtext-eclipse#841] address removal of equinox.ds in platform 4.10
  releng/org.eclipse.xtend.tycho.tests.parent/pom.xml
Labels: releng

#612 [eclipse/xtext#1321] bootstrap against 2.16.0.M1
  gradle/versions.gradle
  releng/org.eclipse.xtend.tycho.parent/pom.xml
Labels: releng

#621 Updated xtext-gradle-plugin to 2.0.2
  gradle/versions.gradle
Labels: releng

#622 [eclipse/xtext#1325] switch to ASM 7
  gradle/versions.gradle
  org.eclipse.xtend.caliper.tests/META-INF/MANIFEST.MF
  org.eclipse.xtend.core.tests.java8/META-INF/MANIFEST.MF
  org.eclipse.xtend.core.tests/META-INF/MANIFEST.MF
  org.eclipse.xtend.core/META-INF/MANIFEST.MF
  org.eclipse.xtend.examples/projects/xtend-annotation-examples/META-INF/MANIFEST.MF
  org.eclipse.xtend.maven.plugin/src/main/java/org/eclipse/xtend/maven/ClassFileDebugSourceExtractor.java
  org.eclipse.xtend.maven.plugin/src/test/java/org/eclipse/xtend/maven/ClassFileDebugInfoExtractor.java
  releng/org.eclipse.xtend.maven.parent/pom.xml
  releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target
  releng/org.eclipse.xtend.target/org.eclipse.xtend.target-oxygen.target
  releng/org.eclipse.xtend.target/org.eclipse.xtend.target-photon.target
  releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201809.target
Labels: releng
