Repository eclipse/xtext-xtend, pull requests merged in 2018-08, with the labels that each got.

#531 [doc] Extend javaSourceVersion doc for Java 9&10
  org.eclipse.xtend.maven.plugin/src/main/java/org/eclipse/xtend/maven/AbstractXtendCompilerMojo.java
Labels: documentation

#535 [#534] Upgrade maven-javadoc-plugin version
  releng/org.eclipse.xtend.maven.parent/pom.xml
Labels: releng

#538 [eclipse/xtext#1267] Update to Gradle 4.9
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: releng

#539 better workaround for signing issue
  releng/org.eclipse.xtend.tycho.parent/pom.xml
Labels: releng

#545 [#164] Add a test case reproducing the issue (currently ignored).
  org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/refactoring/XtendRenameRefactoringTest.xtend
  org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/refactoring/XtendRenameRefactoringTest.java
Labels: bug
