Repository eclipse/xtext-xtend, pull requests merged in 2019-08, with the labels that each got.

#902 [eclipse/xtext#1526] Remove old CBI.Jenkinsfile
  CBI.Jenkinsfile
Labels: releng

#905 [eclipse/xtext-lib#224] Stable method order when using Delegate
  org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/DelegateCompilerTest.xtend
  org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/compiler/DelegateCompilerTest.java
  org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/macro/CodeGenerationContextImpl.java
  org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/macro/TransformationContextImpl.java
  org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/macro/ValidationContextImpl.java
Labels: bug

#906 [eclipse/xtext-eclipse#1155] Avoid unconditonal cast to IXtextDocument
  org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/contentassist/javadoc/XtendJavaDocContentAssistProcessor.java
  org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/editor/OverrideIndicatorRulerAction.java
Labels: enhancement

#907 preserve parameter names during compilation with tycho
  releng/org.eclipse.xtend.tycho.parent/pom.xml
Labels: releng

#910 bootstrap against m3
  gradle/versions.gradle
  org.eclipse.xtend.maven.plugin/src/test/resources/it/pom.xml
  releng/org.eclipse.xtend.tycho.parent/pom.xml
Labels: releng
