Repository eclipse/xtext-xtend, pull requests merged in 2019-02, with the labels that each got.

#703 [eclipse/xtext#1391] pin guava version to 21
  org.eclipse.xtend.caliper.tests/META-INF/MANIFEST.MF
  org.eclipse.xtend.core.tests.java8/META-INF/MANIFEST.MF
  org.eclipse.xtend.core.tests/META-INF/MANIFEST.MF
  org.eclipse.xtend.examples/projects/xtend-annotation-examples-client/META-INF/MANIFEST.MF
  org.eclipse.xtend.examples/projects/xtend-annotation-examples/META-INF/MANIFEST.MF
Labels: releng

#711 [eclipse/xtext#1274] Updated .classpath by Gradle
  org.eclipse.xtend.core.tests.java8/.classpath
  org.eclipse.xtend.core.tests/.classpath
  org.eclipse.xtend.core.tests/org.eclipse.xtend.core.tests.smoke-suites.launch
  org.eclipse.xtend.core/.classpath
  org.eclipse.xtend.ide.common/.classpath
Labels: releng

#713 [eclipse/xtext#1394] bootstrap against 2.17.0.M2
  gradle/versions.gradle
  org.eclipse.xtend.maven.plugin/src/test/resources/it/pom.xml
  releng/org.eclipse.xtend.tycho.parent/pom.xml
Labels: releng

#720 [eclipse/xtext-xtend#415] use textual multi quickfix for remove unnec modifier
  org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/quickfix/QuickfixTest.xtend
  org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/quickfix/QuickfixTest.java
  org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/quickfix/XtendQuickfixProvider.java
Labels: bug

#723 fixed guava deprecations
  org.eclipse.xtend.core/src/org/eclipse/xtend/core/macro/declaration/CompilationUnitImpl.xtend
  org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/macro/declaration/CompilationUnitImpl.java
  org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/resource/ResourceStorageTest.xtend
  org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/resource/ResourceStorageTest.java
Labels: refactoring

#718 [eclipse/xtext#1283] update to MWE 2.10
  releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target
Labels: releng

#726 add mavenCentral repository
  gradle/upstream-repositories.gradle
Labels: releng

#728 Add xtend-gen sources
  org.eclipse.xtend.examples/projects/xtend-euler/.gitignore
  org.eclipse.xtend.examples/projects/xtend-euler/xtend-gen/euler/SolutionTriangle.java
  org.eclipse.xtend.examples/projects/xtend-euler/xtend-gen/euler/Solution_001.java
  org.eclipse.xtend.examples/projects/xtend-euler/xtend-gen/euler/Solution_002.java
  org.eclipse.xtend.examples/projects/xtend-euler/xtend-gen/euler/Solution_003.java
  org.eclipse.xtend.examples/projects/xtend-euler/xtend-gen/euler/Solution_004.java
  org.eclipse.xtend.examples/projects/xtend-euler/xtend-gen/euler/Solution_005.java
  org.eclipse.xtend.examples/projects/xtend-euler/xtend-gen/euler/Solution_006.java
  org.eclipse.xtend.examples/projects/xtend-euler/xtend-gen/euler/Solution_007.java
  org.eclipse.xtend.examples/projects/xtend-euler/xtend-gen/euler/Solution_008.java
  org.eclipse.xtend.examples/projects/xtend-euler/xtend-gen/euler/Solution_009.java
  org.eclipse.xtend.examples/projects/xtend-euler/xtend-gen/euler/Solution_010.java
  org.eclipse.xtend.examples/projects/xtend-euler/xtend-gen/euler/Solution_011.java
  org.eclipse.xtend.examples/projects/xtend-euler/xtend-gen/euler/Solution_012.java
  org.eclipse.xtend.examples/projects/xtend-euler/xtend-gen/euler/Solution_013.java
  org.eclipse.xtend.examples/projects/xtend-euler/xtend-gen/euler/Solution_014.java
  org.eclipse.xtend.examples/projects/xtend-euler/xtend-gen/euler/Solution_015.java
  org.eclipse.xtend.examples/projects/xtend-euler/xtend-gen/euler/Solution_015b.java
  org.eclipse.xtend.examples/projects/xtend-euler/xtend-gen/euler/Solution_016.java
  org.eclipse.xtend.examples/projects/xtend-euler/xtend-gen/euler/Solution_017.java
  org.eclipse.xtend.examples/projects/xtend-euler/xtend-gen/euler/Solution_018.java
  org.eclipse.xtend.examples/projects/xtend-euler/xtend-gen/euler/Solution_019.java
  org.eclipse.xtend.examples/projects/xtend-euler/xtend-gen/euler/Solution_020.java
  org.eclipse.xtend.examples/projects/xtend-euler/xtend-gen/euler/Solution_021.java
  org.eclipse.xtend.examples/projects/xtend-euler/xtend-gen/euler/Solution_022.java
  org.eclipse.xtend.examples/projects/xtend-euler/xtend-gen/euler/Solution_023.java
  org.eclipse.xtend.examples/projects/xtend-euler/xtend-gen/euler/Solution_025.java
  org.eclipse.xtend.examples/projects/xtend-euler/xtend-gen/euler/Solution_067.java
Labels: codegen

#727 [eclipse/xtext#1283] Remove mavenCentral again
  gradle/upstream-repositories.gradle
Labels: releng

#707 [#469] Refactored to use annotation API
  1-gradle-build.sh
  2-maven-build.sh
  org.eclipse.xtend.maven.plugin/pom.xml
  org.eclipse.xtend.maven.plugin/src/main/java/org/eclipse/xtend/maven/AbstractXtendCompilerMojo.java
  org.eclipse.xtend.maven.plugin/src/main/java/org/eclipse/xtend/maven/AbstractXtendInstallDebugInfoMojo.java
  org.eclipse.xtend.maven.plugin/src/main/java/org/eclipse/xtend/maven/AbstractXtendMojo.java
  org.eclipse.xtend.maven.plugin/src/main/java/org/eclipse/xtend/maven/XtendCompile.java
  org.eclipse.xtend.maven.plugin/src/main/java/org/eclipse/xtend/maven/XtendInstallDebugInfo.java
  org.eclipse.xtend.maven.plugin/src/main/java/org/eclipse/xtend/maven/XtendTestCompile.java
  org.eclipse.xtend.maven.plugin/src/main/java/org/eclipse/xtend/maven/XtendTestInstallDebugInfo.java
  releng/org.eclipse.xtend.maven.parent/pom.xml
Labels: refactoring

#731 [#719] Corrected Typos in Issuemessage and AnnotationTest.
  org.eclipse.xtend.core/src/org/eclipse/xtend/core/validation/XtendValidator.java
  org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/quickfix/ValidationIssue719QuickFixTest.xtend
  org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/quickfix/ValidationIssue719QuickFixTest.java
Labels: bug
