Repository eclipse/xtext-xtend, pull requests merged in 2019-05, with the labels that each got.

#791 Ade asm710
  org.eclipse.xtend.core.tests.java8/META-INF/MANIFEST.MF
  org.eclipse.xtend.core.tests/META-INF/MANIFEST.MF
  org.eclipse.xtend.core/META-INF/MANIFEST.MF
  org.eclipse.xtend.examples/projects/xtend-annotation-examples/META-INF/MANIFEST.MF
  releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target
  releng/org.eclipse.xtend.target/org.eclipse.xtend.target-oxygen.target
  releng/org.eclipse.xtend.target/org.eclipse.xtend.target-photon.target
  releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201809.target
  releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201812.target
  releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201903.target
Labels: releng

#796 regenerated docs from website
  org.eclipse.xtend.doc/contents/203_xtend_expressions.html
  org.eclipse.xtend.doc/contents/toc.xml
Labels: documentation

#798 [eclipse/xtext#1437] Bootstrap against 2.18.0.M2
  gradle/versions.gradle
  org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/EmfModelsTest.java
  org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/imports/AbstractRewritableImportSectionTest.java
  org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/javaconverter/JavaConverterTest.java
  org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/lib/PathTest.java
  org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/macro/declaration/ConstantExpressionsInterpreterTest.java
  org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/macro/declaration/DeclarationsTest.java
  org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/resource/ResourceStorageTest.java
  org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/typesystem/ReorderedFeatureCallArgumentsTest.java
  org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/typesystem/ReorderedVarArgFeatureCallArgumentsTest.java
  org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/typesystem/StandardFeatureCallArgumentsTest.java
  org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/typesystem/VarArgFeatureCallArgumentsTest.java
  org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/javaconverter/JavaASTFlattener.java
  org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/macro/AbstractFileSystemSupport.java
  org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/macro/declaration/ProblemSupportImpl.java
  org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/editor/XbaseEditorOpenClassFileTest.java
  org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/macros/AbstractReusableActiveAnnotationTests.java
  org.eclipse.xtend.maven.plugin/src/test/resources/it/pom.xml
  releng/org.eclipse.xtend.tycho.parent/pom.xml
Labels: releng

#797 update to gradle 5.4.1
  gradle/wrapper/gradle-wrapper.properties
Labels: releng

#817 Use classgraph library to scan classpath contents
  org.eclipse.xtend.core.tests/.classpath
  org.eclipse.xtend.core/src/org/eclipse/xtend/core/javaconverter/ASTParserFactory.xtend
  org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/javaconverter/ASTParserFactory.java
Labels: enhancement

#820 [#818] Avoid the ClasspathScanner on signature of AstParserFactory
  org.eclipse.xtend.core.tests/.classpath
  org.eclipse.xtend.core/src/org/eclipse/xtend/core/javaconverter/ASTParserFactory.xtend
  org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/javaconverter/ASTParserFactory.java
Labels: bug

#823 fixed wrong usage of http
  releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target
Labels: releng

#824 harmonized labels
  Jenkinsfile
Labels: releng
