Repository eclipse/xtext-xtend, pull requests merged in 2019-07, with the labels that each got.

#864 [eclipse/xtext#1384] Convert Jenkinsfile to declarative pipeline
  Jenkinsfile
Labels: releng

#866 [eclipse/xtext#1465] Use declarative JUnit step
  CBI.Jenkinsfile
Labels: releng

#870 [eclipse/xtext#1500] Improve Slack notification
  CBI.Jenkinsfile
  Jenkinsfile
Labels: releng

#868 [eclipse/xtext#1489] update to gradle wrapper 5.5
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: releng

#871 updated xtext gradle plugin to version 2.0.7
  gradle/versions.gradle
Labels: releng

#875 [eclipse/xtext#1510] Remove pollScm trigger
  CBI.Jenkinsfile
Labels: releng

#876 [eclipse/xtext#1508] Trigger downstream build
  CBI.Jenkinsfile
  Jenkinsfile
Labels: releng

#878 [eclipse/xtext#1508] Fix regression
  CBI.Jenkinsfile
  Jenkinsfile
Labels: releng

#879 [eclipse/xtext-extras#389] Improved overload resolution for ambiguous constructor calls
  org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/validation/AmbiguityGH389Test.xtend
  org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/validation/AmbiguityValidationTests.xtend
  org.eclipse.xtend.core.tests/suites/org/eclipse/xtend/core/tests/validation/AmbiguityValidationSuite.java
  org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/validation/AmbiguityGH389Test.java
  org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/validation/AmbiguityValidationTest.java
Labels: bug

#882 [eclipse/xtext#1507] Adjust lsp4j upstream URL / Use env.JENKINS_URL
  gradle/upstream-repositories.gradle
  releng/org.eclipse.xtend.maven.parent/pom.xml
Labels: releng

#883 [eclipse/xtext#1515] fine-tune when slack gets notified
  CBI.Jenkinsfile
Labels: releng

#881 [eclipse/xtext#1509] Bootstrap against 2.19.0.M1
  gradle/versions.gradle
  org.eclipse.xtend.maven.plugin/src/test/resources/it/pom.xml
  releng/org.eclipse.xtend.tycho.parent/pom.xml
Labels: releng

#887 [#886] Log exceptions from annotation processors
  org.eclipse.xtend.core/src/org/eclipse/xtend/core/macro/ActiveAnnotationContext.xtend
  org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/macro/ActiveAnnotationContextProvider.java
Labels: bug

#889 Refactoring the JavaDocHyperlinkingTest test cases.
  org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/hyperlinking/JavaDocHyperlinkingTest.xtend
  org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/hyperlinking/JavaDocHyperlinkingTest.java
Labels: refactoring

#890 [eclipse/xtext#1279] use orbit simrel alias directly
  releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target
  releng/org.eclipse.xtend.target/org.eclipse.xtend.target-oxygen.target
  releng/org.eclipse.xtend.target/org.eclipse.xtend.target-photon.target
  releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201809.target
  releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201812.target
  releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201903.target
  releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201906.target
Labels: releng

#893 [eclipse/xtext#1515] Cleanup notifications
  CBI.Jenkinsfile
Labels: releng

#894 fixed slack notifications
  CBI.Jenkinsfile
Labels: releng

#895 [eclipse/xtext#1526] Replace Jenkinsfile with content of CBI.Jenkinsfile
  Jenkinsfile
Labels: releng

#900 [eclipse/xtext#1513] Add nightly master-trigger to replace trigger job
  CBI.Jenkinsfile
  Jenkinsfile
Labels: releng
