Repository eclipse/xtext-xtend, pull requests merged in 2019-09, with the labels that each got.

#912 [releng] Set version to 2.20.0
  gradle/versions.gradle
  maven-pom.xml
  org.eclipse.xtend.core.tests.java8/META-INF/MANIFEST.MF
  org.eclipse.xtend.core.tests/META-INF/MANIFEST.MF
  org.eclipse.xtend.core/META-INF/MANIFEST.MF
  org.eclipse.xtend.core/pom.xml
  org.eclipse.xtend.doc/META-INF/MANIFEST.MF
  org.eclipse.xtend.doc/pom.xml
  org.eclipse.xtend.examples/META-INF/MANIFEST.MF
  org.eclipse.xtend.examples/pom.xml
  org.eclipse.xtend.examples/projects/xtend-annotation-examples-client/META-INF/MANIFEST.MF
  org.eclipse.xtend.examples/projects/xtend-annotation-examples/META-INF/MANIFEST.MF
  org.eclipse.xtend.examples/projects/xtend-examples/META-INF/MANIFEST.MF
  org.eclipse.xtend.ide.common/META-INF/MANIFEST.MF
  org.eclipse.xtend.ide.common/pom.xml
  org.eclipse.xtend.ide.swtbot.tests/META-INF/MANIFEST.MF
  org.eclipse.xtend.ide.swtbot.tests/pom.xml
  org.eclipse.xtend.ide.tests.data/META-INF/MANIFEST.MF
  org.eclipse.xtend.ide.tests.data/pom.xml
  org.eclipse.xtend.ide.tests/META-INF/MANIFEST.MF
  org.eclipse.xtend.ide.tests/pom.xml
  org.eclipse.xtend.ide/META-INF/MANIFEST.MF
  org.eclipse.xtend.ide/pom.xml
  org.eclipse.xtend.m2e/META-INF/MANIFEST.MF
  org.eclipse.xtend.m2e/pom.xml
  org.eclipse.xtend.maven.archetype/pom.xml
  org.eclipse.xtend.maven.plugin/pom.xml
  org.eclipse.xtend.maven.plugin/src/test/resources/it/pom.xml
  org.eclipse.xtend.performance.tests/META-INF/MANIFEST.MF
  org.eclipse.xtend.performance.tests/pom.xml
  org.eclipse.xtend.standalone/META-INF/MANIFEST.MF
  org.eclipse.xtend.standalone/pom.xml
  org.eclipse.xtend.swtbot/META-INF/MANIFEST.MF
  org.eclipse.xtend.swtbot/pom.xml
  releng/org.eclipse.xtend.maven.parent/pom.xml
  releng/org.eclipse.xtend.p2-repository/category.xml
  releng/org.eclipse.xtend.p2-repository/pom.xml
  releng/org.eclipse.xtend.target/pom.xml
  releng/org.eclipse.xtend.tycho.parent/pom.xml
  releng/org.eclipse.xtend.tycho.tests.parent/pom.xml
  tycho-pom.xml
Labels: releng

#913 [eclipse/xtext#1537] bootstrap against 2.19.0
  gradle/versions.gradle
  org.eclipse.xtend.maven.plugin/src/test/resources/it/pom.xml
  releng/org.eclipse.xtend.tycho.parent/pom.xml
Labels: releng

#911 [eclipse/xtext#1520] update to gradle 5.6.1
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  org.eclipse.xtend.core.tests.java8/.classpath
  org.eclipse.xtend.core.tests/.classpath
Labels: releng

#916 regenerated docs
  org.eclipse.xtend.doc/contents/204_activeannotations.html
Labels: documentation

#918 [eclipse/xtext#1547] use maven-publish instead of maven plugin
  1-gradle-build.sh
  build.gradle
  gradle/developers.gradle
  gradle/maven-deployment.gradle
Labels: releng

#920 [eclipse/xtext#1538] use 4.14 I-Builds repo in latest
  releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target
Labels: releng

#921 [eclipse/xtext#1538] use eclipse 2019-12 in target
  releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target
Labels: releng

#924 [https://github.com/eclipse/xtext/issues/1486]
  org.eclipse.xtend.ide/about.ini
  org.eclipse.xtend.ide/build.properties
  org.eclipse.xtend.ide/xtend32.png
Labels: enhancement

#927 fixed settings.xml config in Jenkinsfile
  Jenkinsfile
Labels: releng

#926 [https://github.com/eclipse/xtext/issues/1486]
  org.eclipse.xtend.ide/build.properties
  org.eclipse.xtend.ide/modeling32.png
Labels: refactoring
