Repository eclipse/xtext-xtend, pull requests merged in 2019-06, with the labels that each got.

#827 [eclipse/xtext#1474] Prepare Master for 2.19
  gradle/versions.gradle
  maven-pom.xml
  org.eclipse.xtend.core.tests.java8/META-INF/MANIFEST.MF
  org.eclipse.xtend.core.tests/META-INF/MANIFEST.MF
  org.eclipse.xtend.core/META-INF/MANIFEST.MF
  org.eclipse.xtend.core/pom.xml
  org.eclipse.xtend.doc/META-INF/MANIFEST.MF
  org.eclipse.xtend.doc/pom.xml
  org.eclipse.xtend.examples/META-INF/MANIFEST.MF
  org.eclipse.xtend.examples/pom.xml
  org.eclipse.xtend.examples/projects/xtend-annotation-examples-client/META-INF/MANIFEST.MF
  org.eclipse.xtend.examples/projects/xtend-annotation-examples/META-INF/MANIFEST.MF
  org.eclipse.xtend.examples/projects/xtend-examples/META-INF/MANIFEST.MF
  org.eclipse.xtend.ide.common/META-INF/MANIFEST.MF
  org.eclipse.xtend.ide.common/pom.xml
  org.eclipse.xtend.ide.swtbot.tests/META-INF/MANIFEST.MF
  org.eclipse.xtend.ide.swtbot.tests/pom.xml
  org.eclipse.xtend.ide.tests.data/META-INF/MANIFEST.MF
  org.eclipse.xtend.ide.tests.data/pom.xml
  org.eclipse.xtend.ide.tests/META-INF/MANIFEST.MF
  org.eclipse.xtend.ide.tests/pom.xml
  org.eclipse.xtend.ide/META-INF/MANIFEST.MF
  org.eclipse.xtend.ide/pom.xml
  org.eclipse.xtend.m2e/META-INF/MANIFEST.MF
  org.eclipse.xtend.m2e/pom.xml
  org.eclipse.xtend.maven.archetype/pom.xml
  org.eclipse.xtend.maven.plugin/pom.xml
  org.eclipse.xtend.maven.plugin/src/test/resources/it/pom.xml
  org.eclipse.xtend.performance.tests/META-INF/MANIFEST.MF
  org.eclipse.xtend.performance.tests/pom.xml
  org.eclipse.xtend.standalone/META-INF/MANIFEST.MF
  org.eclipse.xtend.standalone/pom.xml
  org.eclipse.xtend.swtbot/META-INF/MANIFEST.MF
  org.eclipse.xtend.swtbot/pom.xml
  releng/org.eclipse.xtend.maven.parent/pom.xml
  releng/org.eclipse.xtend.p2-repository/category.xml
  releng/org.eclipse.xtend.p2-repository/pom.xml
  releng/org.eclipse.xtend.target/pom.xml
  releng/org.eclipse.xtend.tycho.parent/pom.xml
  releng/org.eclipse.xtend.tycho.tests.parent/pom.xml
  tycho-pom.xml
Labels: releng

#829 [eclipse/xtext#1475] build against orbit 2019-09
  releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target
  releng/org.eclipse.xtend.target/org.eclipse.xtend.target-oxygen.target
  releng/org.eclipse.xtend.target/org.eclipse.xtend.target-photon.target
  releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201809.target
  releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201812.target
  releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201903.target
Labels: releng

#828 [eclipse/xtext#1473] bootstrap against 2.18
  gradle/versions.gradle
  org.eclipse.xtend.maven.plugin/src/test/resources/it/pom.xml
  releng/org.eclipse.xtend.tycho.parent/pom.xml
Labels: releng

#832 [eclipse/xtext#1467] Add JIRO as known environment qualifier for buil…
  CBI.Jenkinsfile
Labels: releng

#835 [eclipse/xtext#1463] Configure timeout & timestamps
  CBI.Jenkinsfile
  Jenkinsfile
Labels: releng

#836 Refactoring the XtendFoldingRegionProviderTest class.
  org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/folding/XtendFoldingRegionProviderTest.java
Labels: refactoring

#838 [eclipse/xtext#1485] update to mwe 2.11
  releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target
Labels: releng

#841 bumped grgit plugin
  build.gradle
Labels: releng

#844 [eclipse/xtext#1490] Bump xtext-gradle-plugin to 2.0.5
  gradle/versions.gradle
Labels: releng

#843 speedup longrunning test: avoid extensive calls to classpathtypeprovider
  org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/richstring/RichStringCompilerTest.java
  org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/validation/RichStringValidationTest.java
Labels: performance

#845 [eclipse/xtext-extras#445] Test cases
  org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/linking/LinkingErrorTest.java
Labels: bug

#846 [eclipse/xtext-xtend#818] Add classgraph to target platform
  org.eclipse.xtend.core/src/org/eclipse/xtend/core/javaconverter/ASTParserFactory.xtend
  org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/javaconverter/ASTParserFactory.java
  org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/javaconverter/PasteJavaCodeHandler.java
  releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target
  releng/org.eclipse.xtend.target/org.eclipse.xtend.target-oxygen.target
  releng/org.eclipse.xtend.target/org.eclipse.xtend.target-photon.target
  releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201809.target
  releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201812.target
  releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201903.target
  releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201906.target
Labels: enhancement

#848 performance opt. longrunning tests
  org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/CompilerTestHelper.java
Labels: performance

#849 More Perf. Improvements Longrunning tests
  org.eclipse.xtend.core.tests/longrunning/src/org/eclipse/xtend/core/tests/richstring/RichStringWithCommentCompilerTest.java
  org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/CompilerTestHelper.java
  org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/richstring/NoImplicitImportsRuntimeInjectorProvider.java
  org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/richstring/RichStringCompilerTest.java
  org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/richstring/RichStringCompilerTest2.java
  org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/validation/RichStringValidationTest.java
Labels: performance

#850 [eclipse/xtext#1491] harmoized target_platform variable in Jenkinsfile
  CBI.Jenkinsfile
Labels: releng

#851 [eclipse/xtext1475] use 2019-09 in latest target platform
  releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target
Labels: releng

#853 [#852] moved longrunning tests to normal tests
  4-gradle-longrunning-tests.sh
  CBI.Jenkinsfile
  Jenkinsfile
  gradle/longrunning-tests.gradle
  org.eclipse.xtend.core.tests/.classpath
  org.eclipse.xtend.core.tests/build.gradle
  org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/richstring/InitialIndentationWithCommentsTest.java
  org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/richstring/RichStringWithCommentCompilerTest.java
  org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/richstring/RichStringWithCommentProcessorTest.java
  org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/richstring/RichStringWithCommentValidationTest.java
  org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/smoke/AbstractSmokeTest.java
  org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/smoke/Case_0.xtend
  org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/smoke/Case_1.xtend
  org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/smoke/Case_14.xtend
  org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/smoke/Case_2.xtend
  org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/smoke/Case_3.xtend
  org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/smoke/Case_4.xtend
  org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/smoke/Case_5.xtend
  org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/smoke/Case_6.xtend
  org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/smoke/Case_7.xtend
  org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/smoke/Case_8.xtend
  org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/smoke/Case_9.xtend
  org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/smoke/SmokeTest.java
  org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/smoke/SmokeTestCases.xtend
  org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/smoke/Case_0.java
  org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/smoke/Case_1.java
  org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/smoke/Case_14.java
  org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/smoke/Case_2.java
  org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/smoke/Case_3.java
  org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/smoke/Case_4.java
  org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/smoke/Case_5.java
  org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/smoke/Case_6.java
  org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/smoke/Case_7.java
  org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/smoke/Case_8.java
  org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/smoke/Case_9.java
  org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/smoke/SmokeTestCases.java
Labels: releng

#855 [eclipse/xtext-core#1178] Use one 1 cpu in every pod
  CBI.Jenkinsfile
Labels: releng

#857 bumped io.spring.dependency-management plugin
  gradle/versions.gradle
Labels: releng

#858 [eclipse/xtext#1495] Use unique label for each agent
  CBI.Jenkinsfile
Labels: releng

#860 [eclipse/xtext#1431] Tweak resource constraints
  CBI.Jenkinsfile
Labels: releng

#861 [eclipse/xtext-extras#343] Test case
  org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/builder/XtendBuilderParticipantTest.java
Labels: bug
