Repository eclipse/xtext-xtend, pull requests merged in 2019-04, with the labels that each got.

#760 use https to access typefox jenkins #759
  README.md
  gradle/bootstrap-setup.gradle
  gradle/upstream-repositories.gradle
  releng/org.eclipse.xtend.maven.parent/pom.xml
  releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target
  releng/org.eclipse.xtend.target/org.eclipse.xtend.target-oxygen.target
  releng/org.eclipse.xtend.target/org.eclipse.xtend.target-photon.target
  releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201809.target
  releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201812.target
  releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201903.target
  releng/org.eclipse.xtend.tycho.parent/pom.xml
Labels: releng

#762 [eclipse/xtext#1423] Update Gradle Wrapper to Version 5.3.1
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: releng

#761 Remove IDEA since the support has been dropped.
  README.md
  org.eclipse.xtend.core/GenerateXtend.mwe2.launch
  org.eclipse.xtend.core/generator/org/eclipse/xtend/core/parser/XtendLanguageGeneratorModule.java
  org.eclipse.xtend.core/generator/org/eclipse/xtend/core/parser/XtendPsiAntlrGrammarGenerator.java
  org.eclipse.xtend.core/src/org/eclipse/xtend/core/GenerateXtend.mwe2
Labels: restructuring

#763 [eclipse/xtext#1424] Change default Jenkins
  README.md
  gradle/bootstrap-setup.gradle
  gradle/upstream-repositories.gradle
  releng/org.eclipse.xtend.maven.parent/pom.xml
  releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target
  releng/org.eclipse.xtend.target/org.eclipse.xtend.target-oxygen.target
  releng/org.eclipse.xtend.target/org.eclipse.xtend.target-photon.target
  releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201809.target
  releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201812.target
  releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201903.target
  releng/org.eclipse.xtend.tycho.parent/pom.xml
Labels: releng

#765 [eclipse/xtext#1424] Change default Jenkins
  README.md
Labels: releng

#764 Use mavenCentral instead of jcenter to avoid sync delays and stability issues
  build.gradle
  gradle/bootstrap-setup.gradle
  gradle/upstream-repositories.gradle
Labels: releng

#766 replaced tf jenkins with ci.eclipse.org/xtext for lsp4j
  gradle/upstream-repositories.gradle
  releng/org.eclipse.xtend.maven.parent/pom.xml
Labels: releng

#768 #767 Avoid try/finally to avoid exception swallow and fix cleanup.
  org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/refactoring/JavaRefactoringIntegrationTest.java
Labels: unittest

#770 [eclipse/xtext#1173] set discouraged access to warning
  org.eclipse.xtend.caliper.tests/.settings/org.eclipse.jdt.core.prefs
  org.eclipse.xtend.core.tests.java8/.settings/org.eclipse.jdt.core.prefs
  org.eclipse.xtend.core.tests/.settings/org.eclipse.jdt.core.prefs
  org.eclipse.xtend.core/.settings/org.eclipse.jdt.core.prefs
  org.eclipse.xtend.ide.swtbot.tests/.settings/org.eclipse.jdt.core.prefs
  org.eclipse.xtend.ide.tests/.settings/org.eclipse.jdt.core.prefs
  org.eclipse.xtend.performance.tests/.settings/org.eclipse.jdt.core.prefs
Labels: releng

#773 #767 Clear every file from source folder on cleanup.
  org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/refactoring/JavaRefactoringIntegrationTest.java
Labels: unittest

#774 [xtext-extras#403] Fixed regression in injector provider
  org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/RuntimeInjectorProvider.java
  org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/RuntimeInjectorProvider.java
Labels: bug

#776 Change defaultGoal to install
  releng/org.eclipse.xtend.p2-repository/pom.xml
  tycho-pom.xml
Labels: bug, releng

#775 [eclipse/xtext#1422] update to tycho 1.4.0
  releng/org.eclipse.xtend.maven.parent/pom.xml
  releng/org.eclipse.xtend.tycho.parent/pom.xml
Labels: releng

#778 [eclipse/xtext#1430] added missing tp to CBI
  CBI.Jenkinsfile
Labels: releng

#781 [#777] Make JavaClasspathTest compatible to latest
  org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/buildpath/JavaClasspathTest.java
Labels: bug

#769 [xtext-eclipse#397] Support for ternary expressions and try with resource
  org.eclipse.xtend.core.tests.java8/src/org/eclipse/xtend/core/tests/java8/compiler/TryWithResourcesTestJava8.xtend
  org.eclipse.xtend.core.tests.java8/src/org/eclipse/xtend/core/tests/java8/javaconverter/Java8ConverterTest.xtend
  org.eclipse.xtend.core.tests.java8/xtend-gen/org/eclipse/xtend/core/tests/java8/compiler/TryWithResourcesTestJava8.java
  org.eclipse.xtend.core.tests.java8/xtend-gen/org/eclipse/xtend/core/tests/java8/javaconverter/Java8ConverterTest.java
  org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/CompilerTest.java
  org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/TryWithResourcesTest.xtend
  org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/formatting/XtendConditionalExpressionFormatterTest.xtend
  org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/javaconverter/JavaConverterTest.xtend
  org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/validation/CheckedExceptionTest.java
  org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/validation/ValidationIssue397Test.xtend
  org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/compiler/TryWithResourcesTest.java
  org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/formatting/XtendConditionalExpressionFormatterTest.java
  org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/javaconverter/JavaConverterTest.java
  org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/validation/ValidationIssue397Test.java
  org.eclipse.xtend.core/src-gen/org/eclipse/xtend/core/Xtend.xtextbin
  org.eclipse.xtend.core/src-gen/org/eclipse/xtend/core/parser/antlr/internal/DebugInternalXtend.g
  org.eclipse.xtend.core/src-gen/org/eclipse/xtend/core/parser/antlr/internal/InternalXtend.g
  org.eclipse.xtend.core/src-gen/org/eclipse/xtend/core/parser/antlr/internal/InternalXtend.tokens
  org.eclipse.xtend.core/src-gen/org/eclipse/xtend/core/parser/antlr/internal/InternalXtendLexer.java
  org.eclipse.xtend.core/src-gen/org/eclipse/xtend/core/parser/antlr/internal/InternalXtendParser.java
  org.eclipse.xtend.core/src-gen/org/eclipse/xtend/core/serializer/AbstractXtendSemanticSequencer.java
  org.eclipse.xtend.core/src-gen/org/eclipse/xtend/core/serializer/AbstractXtendSyntacticSequencer.java
  org.eclipse.xtend.core/src-gen/org/eclipse/xtend/core/services/XtendGrammarAccess.java
  org.eclipse.xtend.core/src/org/eclipse/xtend/core/Xtend.xtext
  org.eclipse.xtend.core/src/org/eclipse/xtend/core/formatting2/XtendFormatter.xtend
  org.eclipse.xtend.core/src/org/eclipse/xtend/core/javaconverter/JavaASTFlattener.xtend
  org.eclipse.xtend.core/src/org/eclipse/xtend/core/javaconverter/JavaConverter.xtend
  org.eclipse.xtend.core/src/org/eclipse/xtend/core/validation/IssueCodes.java
  org.eclipse.xtend.core/src/org/eclipse/xtend/core/validation/XtendConfigurableIssueCodes.java
  org.eclipse.xtend.core/src/org/eclipse/xtend/core/validation/XtendValidator.java
  org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/formatting2/XtendFormatter.java
  org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/javaconverter/JavaASTFlattener.java
  org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/javaconverter/JavaConverter.java
  org.eclipse.xtend.ide.common/src-gen/org/eclipse/xtend/ide/common/contentassist/antlr/XtendParser.java
  org.eclipse.xtend.ide.common/src-gen/org/eclipse/xtend/ide/common/contentassist/antlr/internal/InternalXtend.g
  org.eclipse.xtend.ide.common/src-gen/org/eclipse/xtend/ide/common/contentassist/antlr/internal/InternalXtend.tokens
  org.eclipse.xtend.ide.common/src-gen/org/eclipse/xtend/ide/common/contentassist/antlr/internal/InternalXtendLexer.java
  org.eclipse.xtend.ide.common/src-gen/org/eclipse/xtend/ide/common/contentassist/antlr/internal/InternalXtendParser.java
  org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/quickfix/ValidationIssue397QuickFixTest.xtend
  org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/contentassist/ContentAssistTest.java
  org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/quickfix/ValidationIssue397QuickFixTest.java
  org.eclipse.xtend.ide/src-gen/org/eclipse/xtend/ide/contentassist/AbstractXtendProposalProvider.java
  org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/contentassist/XtendProposalProvider.java
  org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/javaconverter/PasteJavaCodeHandler.java
  org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/quickfix/XtendQuickfixProvider.java
  org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/validator/preferences/XtendValidatorConfigurationBlock.java
Labels: new_feature
