Repository eclipse/xtext-xtend, pull requests merged in 2020-10, with the labels that each got.

#1123 [eclipse/xtext#1852] Update to ASM 9
  org.eclipse.xtend.core.tests.java8/META-INF/MANIFEST.MF
  org.eclipse.xtend.core.tests/META-INF/MANIFEST.MF
  org.eclipse.xtend.core/META-INF/MANIFEST.MF
  org.eclipse.xtend.examples/projects/xtend-annotation-examples/META-INF/MANIFEST.MF
  org.eclipse.xtend.maven.plugin/src/main/java/org/eclipse/xtend/maven/ClassFileDebugSourceExtractor.java
  org.eclipse.xtend.maven.plugin/src/test/java/org/eclipse/xtend/maven/ClassFileDebugInfoExtractor.java
  releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target
  releng/org.eclipse.xtend.target/org.eclipse.xtend.target-oxygen.target
  releng/org.eclipse.xtend.target/org.eclipse.xtend.target-photon.target
  releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201809.target
  releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201812.target
  releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201903.target
  releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201906.target
  releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201909.target
  releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201912.target
  releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202003.target
  releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202006.target
  releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202009.target
Labels: releng

#1124 update grgit
  build.gradle
Labels: releng

#1125 [NONE] Fix missing params issue
  Jenkinsfile
Labels: releng

#1126 [releng] Bootstrap against 2.24.0.M1
  gradle/versions.gradle
  org.eclipse.xtend.maven.plugin/src/test/resources/it/pom.xml
  releng/org.eclipse.xtend.tycho.parent/pom.xml
Labels: bot, releng

#1130 Bug 568152 - Use FrameworkUtil#getBundle instead of Platform#getBundle
  org.eclipse.xtend.ide/src-gen/org/eclipse/xtend/ide/XtendExecutableExtensionFactory.java
Labels: enhancement

#1131 Bug 568152 - Use FrameworkUtil#getBundle instead of Platform#getBundle
  org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/refactoring/JavaRefactoringIntegrationTest.java
Labels: enhancement

#1133 [eclipse/xtext-xtend#1132] do restriction checks also on type literal member feature calls
  org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/validation/AccessRestrictionInWorkspaceTest.xtend
  org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/validation/AccessRestrictionInWorkspaceTest.java
Labels: bug

#1134 [eclipse/xtext#1866] update to MWE(2) 1.6.0/2.12.0 M2
  releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target
Labels: releng
