Repository eclipse/xtext-xtend, pull requests merged in 2020-01, with the labels that each got.

#980 Refactor usage of Wrapper constructors to valueOf
  org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/AbstractXbaseEvaluationTest.java
  org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/formatting/preferences/AbstractProfileManager.java
Labels: refactoring

#989 [#988] performance optimization console hyperlinking regex
  org.eclipse.xtend.ide/plugin.xml
Labels: enhancement, performance

#990 [eclipse/xtext#1642] regenerated xtend code with latest xtend
  org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/macro/AnnotationWithNestedAnnotations.java
  org.eclipse.xtend.examples/projects/xtend-annotation-examples-client/xtend-gen/extract/ExtractExampleInterface.java
  org.eclipse.xtend.ide.common/xtend-gen/org/eclipse/xtend/ide/common/highlighting/XtendHighlightingStyles.java
  org.eclipse.xtend.ide.common/xtend-gen/org/eclipse/xtend/ide/common/outline/IXtendOutlineContext.java
  org.eclipse.xtend.ide.common/xtend-gen/org/eclipse/xtend/ide/common/outline/IXtendOutlineNodeBuilder.java
  org.eclipse.xtend.ide.common/xtend-gen/org/eclipse/xtend/ide/common/outline/IXtendOutlineTreeBuilder.java
Labels: releng

#995 [releng] Bootstrap against 2.21.0.M1
  gradle/versions.gradle
  org.eclipse.xtend.maven.plugin/src/test/resources/it/pom.xml
  releng/org.eclipse.xtend.tycho.parent/pom.xml
Labels: bot, releng

#996 update grgit to 4.0.1
  build.gradle
Labels: releng

#992 [eclipse/xtext#1644] use java platform
  build.gradle
  gradle/versions.gradle
Labels: releng

#997 [eclipse/xtext#1643] update to tycho 1.6.0
  releng/org.eclipse.xtend.maven.parent/pom.xml
  releng/org.eclipse.xtend.tycho.parent/pom.xml
Labels: releng

#998 [eclipse/xtext#1595] Escape branch name for k8s label
  Jenkinsfile
Labels: releng

#1000 removed duplicate extra requirement
  releng/org.eclipse.xtend.tycho.tests.parent/pom.xml
Labels: releng
